
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  csSidebar: [
    {
      type: 'autogenerated',
      dirName: 'cs', 
    },
  ],
  csinterviewSidebar:[
    {
      type: 'autogenerated',
      dirName: 'csinterview', 
    },
  ],
  csprojectSidebar:[
    {
      type: 'autogenerated',
      dirName: 'csproject', 
    },
  ],
  goSidebar: [
    {
      type: 'autogenerated',
      dirName: 'go', 
    },
  ],
  jsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'js', 
    },
  ],
  jsinterviewSidebar: [
    {
      type: 'autogenerated',
      dirName: 'jsinterview', 
    },
  ],
  jsprojectSidebar: [
    {
      type: 'autogenerated',
      dirName: 'jsproject', 
    },
  ],
  javaSidebar: [
    {
      type: 'autogenerated',
      dirName: 'java', 
    },
  ],
  javainterviewSidebar: [
    {
      type: 'autogenerated',
      dirName: 'javainterview', 
    },
  ],
  javaprojectSidebar: [
    {
      type: 'autogenerated',
      dirName: 'javaproject', 
    },
  ],
  pythonSidebar: [
    {
      type: 'autogenerated',
      dirName: 'python', 
    },
  ],
  cppSidebar: [
    {
      type: 'autogenerated',
      dirName: 'cpp', 
    },
  ],
  // mathSidebar: [
  //   {
  //     type: 'autogenerated',
  //     dirName: 'math', 
  //   },
  // ],

  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;
