
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  csSidebar: [
    {
      type: 'autogenerated',
      dirName: 'cs', 
    },
  ],
  electiveSidebar:[
    {
      type: 'autogenerated',
      dirName: 'elective', 
    },
  ],
  mathSidebar:[
    {
      type: 'autogenerated',
      dirName: 'math', 
    },
  ],
  goSidebar: [
    {
      type: 'autogenerated',
      dirName: 'go', 
    },
  ],
  jsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'js', 
    },
  ],
  javaSidebar: [
    {
      type: 'autogenerated',
      dirName: 'java', 
    },
  ],
  pythonSidebar: [
    {
      type: 'autogenerated',
      dirName: 'python', 
    },
  ],
  cppSidebar: [
    {
      type: 'autogenerated',
      dirName: 'cpp', 
    },
  ],
  aiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'AI', 
    },
  ],


  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;
