
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  csSidebar: [
    {
      type: 'autogenerated',
      dirName: 'cs', 
    },
  ],
  mathSidebar:[
    {
      type: 'autogenerated',
      dirName: 'math', 
    },
  ],

  aiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'AI', 
    },
  ],


  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;
